# name: autoBuild
# on:
#   push:
#     branches:
#       - master
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.x
#       - run: pip install -r requirements.txt
#       - run: mkdocs gh-deploy --force
#       - uses: peaceiris/actions-gh-pages@v3
#         with:
#           personal_token: ${{ secrets.TOKEN }}
#           publish_dir: ./publish
#           publish_branch: gh-pages
#           keep_files: true
name: autoBuild

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mkdocs-toolchain
        uses: actions/checkout@v2
        with:
          repository: TonyCrane/mkdocs-toolchain
          path: plugins/mkdocs-toolchain
          fetch-depth: 0  # Ensure full history is available

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          cd plugins/mkdocs-toc-plugin
          pip install -r requirements.txt

      - name: Build and deploy Mkdocs
        run: |
          cd plugins/mkdocs-toc-plugin
          mkdocs gh-deploy --force

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
          keep_files: true



