# name: autoBuild
# on:
#   push:
#     branches:
#       - master
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.x
#       - run: pip install -r requirements.txt
#       - run: mkdocs gh-deploy --force
#       - uses: peaceiris/actions-gh-pages@v3
#         with:
#           personal_token: ${{ secrets.TOKEN }}
#           publish_dir: ./publish
#           publish_branch: gh-pages
#           keep_files: true
name: autoBuild

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is available
          submodules: recursive  # Ensure submodules are checked out

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install -r requirements.txt
      - name: Install dependencies
        run: |
          cd plugins/mkdocs-toc-plugin
          python setup.py develop
      - name: Build and deploy Mkdocs
        run: |
          cd plugins/mkdocs-toc-plugin
          mkdocs gh-deploy --force

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
          keep_files: true




# project-root/
# |-- .github/
# |   |-- workflows/
# |       |-- autoBuild.yml
# |-- plugins/
# |   |-- mkdocs-toc-plugin/
# |       |-- mkdocs-toc-plugin/
# |       |-- setup.py
# |   |requirements.txt
# |-- other_files/
# |-- ...


